# <center>Assignment 6</center>

## <center>Regression Using ANN</center>

**Atharva Ramgirkar 19BCE0114**

### <center>Table of Contents</center>

* [Importing Libraries](#1.-Importing-Libraries)
* [Getting the Data](#2.-Getting-the-Data)
* [Looking at the Data](#3.-Looking-at-the-Data)
* [Handling Null Values](#4.-Handling-Null-Values)
    * [Administration Column](#4.1-Administration-Column)
    * [Marketing Spend Column](#4.2-Marketing-Spend-Column)
* [One Hot Encoding](#5.-One-Hot-Encoding)
    * [Column Transformer](#5.1-Column-Transformer)
* [Spliting Data into Features and Target](#6.-Spliting-Data-into-Features-and-Target)
* [Scaling the Data](#7.-Scaling-the-Data)
* [Train Test Split](#8.-Train-Test-Split)
* [Model Building](#9.-Model-Building)
    * [Model Initialization](#9.1-Model-Initialization)
    * [Adding Hidden Layers and Dropout Layers](#9.2-Adding-Hidden-Layers-and-Dropout-Layers)
    * [Adding Output Layer](#9.3-Adding-Output-Layer)
* [Compiling Model](#10.-Compiling-Model)
* [Training Model](#11.-Training-Model)
* [Model Prediction on Individual Observation](#12.-Model-Prediction-on-Individual-Observation)
* [Testing Model](#13.-Testing-Model)
* [RMSE Score](#14.-RMSE-Score)

### 1. Importing Libraries

[Back to Top](#Table-of-Contents)

In [1]:
import pandas as pd
import numpy as np

# To Initialize the model
from tensorflow.keras.models import Sequential 
# To Add layers
from tensorflow.keras.layers import Dense 
# To Add Droupout Layers
from tensorflow.keras.layers import Dropout

import tensorflow as tf
import keras

# Split the Dataset
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score 
import matplotlib.pyplot as plt
%matplotlib inline

# For Encoding 
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# For Scaling 
from sklearn.preprocessing import StandardScaler

import math

### 2. Getting the Data

[Back to Top](#Table-of-Contents)

In [2]:
df = pd.read_csv("50_Startups.csv")

### 3. Looking at the Data

[Back to Top](#Table-of-Contents)

In [3]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
df.shape

(50, 5)

### 4. Handling Null Values 

[Back to Top](#Table-of-Contents)

In [5]:
df.isnull().sum()

R&D Spend          0
Administration     1
Marketing Spend    1
State              0
Profit             0
dtype: int64

In [6]:
df[df['Administration'].isnull()].index.tolist()

[10]

In [7]:
df[df['Marketing Spend'].isnull()].index.tolist()

[6]

#### 4.1 Administration Column

[Back to Top](#Table-of-Contents)

In [8]:
df.iloc[10,:]

R&D Spend          101913.08
Administration           NaN
Marketing Spend    229160.95
State                Florida
Profit             146121.95
Name: 10, dtype: object

In [9]:
df[df['State']=="Florida"]['Administration'].mean()

122513.88333333335

In [3]:
df.loc[10,('Administration')] = df[df['State']=="Florida"]['Administration'].mean()

In [11]:
df.loc[10,:]

R&D Spend              101913.08
Administration     122513.883333
Marketing Spend        229160.95
State                    Florida
Profit                 146121.95
Name: 10, dtype: object

In [12]:
df['Administration'][10]

122513.88333333335

In [13]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    1
State              0
Profit             0
dtype: int64

#### 4.2 Marketing Spend Column

[Back to Top](#Table-of-Contents)

In [14]:
df.iloc[6,:]

R&D Spend           134615.46
Administration      147198.87
Marketing Spend           NaN
State              California
Profit              156122.51
Name: 6, dtype: object

In [15]:
df[df['State']=="California"]['Marketing Spend'].mean()

185967.43624999997

In [4]:
df.loc[6,('Marketing Spend')] = df[df['State']=="California"]['Marketing Spend'].mean()

In [17]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

### 5. One Hot Encoding

[Back to Top](#Table-of-Contents)

In [18]:
df.State.value_counts()

New York      17
California    17
Florida       16
Name: State, dtype: int64

#### 5.1 Column Transformer

[Back to Top](#Table-of-Contents)

In [5]:
ct = ColumnTransformer([("oh",OneHotEncoder(),[0])],
                        remainder = "passthrough")

In [6]:
df_states = pd.DataFrame(ct.fit_transform(df.State.to_numpy().reshape(-1,1)),columns=['NY','Californial','Florida'])

In [21]:
df.State.to_numpy()

array(['New York', 'California', 'Florida', 'New York', 'Florida',
       'New York', 'California', 'Florida', 'New York', 'California',
       'Florida', 'California', 'Florida', 'California', 'Florida',
       'New York', 'California', 'New York', 'Florida', 'New York',
       'California', 'New York', 'Florida', 'Florida', 'New York',
       'California', 'Florida', 'New York', 'Florida', 'New York',
       'Florida', 'New York', 'California', 'Florida', 'California',
       'New York', 'Florida', 'California', 'New York', 'California',
       'California', 'Florida', 'California', 'New York', 'California',
       'New York', 'Florida', 'California', 'New York', 'California'],
      dtype=object)

In [7]:
df = pd.concat([df_states,df],axis=1)
df

NY  Californial  Florida  R&D Spend  Administration  Marketing Spend  \
0   0.0          0.0      1.0  165349.20   136897.800000     471784.10000   
1   1.0          0.0      0.0  162597.70   151377.590000     443898.53000   
2   0.0          1.0      0.0  153441.51   101145.550000     407934.54000   
3   0.0          0.0      1.0  144372.41   118671.850000     383199.62000   
4   0.0          1.0      0.0  142107.34    91391.770000     366168.42000   
5   0.0          0.0      1.0  131876.90    99814.710000     362861.36000   
6   1.0          0.0      0.0  134615.46   147198.870000     185967.43625   
7   0.0          1.0      0.0  130298.13   145530.060000     323876.68000   
8   0.0          0.0      1.0  120542.52   148718.950000     311613.29000   
9   1.0          0.0      0.0  123334.88   108679.170000     304981.62000   
10  0.0          1.0      0.0  101913.08   122513.883333     229160.95000   
11  1.0          0.0      0.0  100671.96    91790.610000     249744.55000   
12  0.0          1.0      0.0   93863.75   127320.380000     249839.44000   
13  1.0          0.0      0.0   91992.39   135495.070000     252664.93000   
14  0.0          1.0      0.0  119943.24   156547.420000     256512.92000   
15  0.0          0.0      1.0  114523.61   122616.840000     261776.23000   
16  1.0          0.0      0.0   78013.11   121597.550000     264346.06000   
17  0.0          0.0      1.0   94657.16   145077.580000     282574.31000   
18  0.0          1.0      0.0   91749.16   114175.790000     294919.57000   
19  0.0          0.0      1.0   86419.70   153514.110000          0.00000   
20  1.0          0.0      0.0   76253.86   113867.300000     298664.47000   
21  0.0          0.0      1.0   78389.47   153773.430000     299737.29000   
22  0.0          1.0      0.0   73994.56   122782.750000     303319.26000   
23  0.0          1.0      0.0   67532.53   105751.030000     304768.73000   
24  0.0          0.0      1.0   77044.01    99281.340000     140574.81000   
25  1.0          0.0      0.0   64664.71   139553.160000     137962.62000   
26  0.0          1.0      0.0   75328.87   144135.980000     134050.07000   
27  0.0          0.0      1.0   72107.60   127864.550000     353183.81000   
28  0.0          1.0      0.0   66051.52   182645.560000     118148.20000   
29  0.0          0.0      1.0   65605.48   153032.060000     107138.38000   
30  0.0          1.0      0.0   61994.48   115641.280000      91131.24000   
31  0.0          0.0      1.0   61136.38   152701.920000      88218.23000   
32  1.0          0.0      0.0   63408.86   129219.610000      46085.25000   
33  0.0          1.0      0.0   55493.95   103057.490000     214634.81000   
34  1.0          0.0      0.0   46426.07   157693.920000     210797.67000   
35  0.0          0.0      1.0   46014.02    85047.440000     205517.64000   
36  0.0          1.0      0.0   28663.76   127056.210000     201126.82000   
37  1.0          0.0      0.0   44069.95    51283.140000     197029.42000   
38  0.0          0.0      1.0   20229.59    65947.930000     185265.10000   
39  1.0          0.0      0.0   38558.51    82982.090000     174999.30000   
40  1.0          0.0      0.0   28754.33   118546.050000     172795.67000   
41  0.0          1.0      0.0   27892.92    84710.770000     164470.71000   
42  1.0          0.0      0.0   23640.93    96189.630000     148001.11000   
43  0.0          0.0      1.0   15505.73   127382.300000      35534.17000   
44  1.0          0.0      0.0   22177.74   154806.140000      28334.72000   
45  0.0          0.0      1.0    1000.23   124153.040000       1903.93000   
46  0.0          1.0      0.0    1315.46   115816.210000     297114.46000   
47  1.0          0.0      0.0       0.00   135426.920000          0.00000   
48  0.0          0.0      1.0     542.05    51743.150000          0.00000   
49  1.0          0.0      0.0       0.00   116983.800000      45173.06000   

         State     Profit  
0     New York  192261.83  
1   California  19179

In [8]:
df = df.drop('State',axis=1)

In [24]:
df.head()

NY  Californial  Florida  R&D Spend  Administration  Marketing Spend  \
0  0.0          0.0      1.0  165349.20       136897.80        471784.10   
1  1.0          0.0      0.0  162597.70       151377.59        443898.53   
2  0.0          1.0      0.0  153441.51       101145.55        407934.54   
3  0.0          0.0      1.0  144372.41       118671.85        383199.62   
4  0.0          1.0      0.0  142107.34        91391.77        366168.42   

      Profit  
0  192261.83  
1  191792.06  
2  191050.39  
3  182901.99  
4  166187.94

In [9]:
df_vals = df.values

### 6. Spliting Data into Features and Target

[Back to Top](#Table-of-Contents)

In [10]:
X = df_vals[:,0:6]
y = df_vals[:,6]

In [27]:
X[0]

array([0.000000e+00, 0.000000e+00, 1.000000e+00, 1.653492e+05,
       1.368978e+05, 4.717841e+05])

In [28]:
y[0]

192261.83

### 7. Scaling the Data

[Back to Top](#Table-of-Contents)

In [11]:
sc = StandardScaler()

In [12]:
X = sc.fit_transform(X)
y = sc.fit_transform(y.reshape(-1,1))

In [31]:
X[0]

array([-0.71774056, -0.68599434,  1.39326109,  2.01641149,  0.55299984,
        2.15371621])

In [32]:
y[0]

array([2.01120333])

### 8. Train Test Split

[Back to Top](#Table-of-Contents)

In [13]:
X_train,X_test,y_train,y_test = train_test_split(X,
                                                 y,
                                                 test_size=0.27,
                                                 random_state=114)

### 9. Model Building

[Back to Top](#Table-of-Contents)

#### 9.1 Model Initialization

In [95]:
# Feed Forward 
model = Sequential()

#### 9.2 Adding Hidden Layers and Dropout Layers

In [96]:
model.add(Dense(units=6,
                kernel_initializer="random_uniform",
                activation="relu"))

model.add(Dropout(0.2))

model.add(Dense(units=6,
                kernel_initializer="random_uniform",
                activation="relu"))

#### 9.3 Adding Output Layer

In [97]:
# output layer
model.add(Dense(units=1,
                kernel_initializer="random_uniform"))

### 10. Compiling Model

[Back to Top](#Table-of-Contents)

In [98]:
optimizer = keras.optimizers.Adam(lr=0.1)
model.compile(optimizer='adam',loss="mse",metrics='mse')

### 11. Training Model

[Back to Top](#Table-of-Contents)

In [99]:
history = model.fit(X_train,y_train,batch_size=5,epochs=1000,validation_data=(X_test,y_test))

Epoch 1/1000
8/8 [==============================] - 0s 15ms/step - loss: 0.9601 - mse: 0.9601 - val_loss: 1.1028 - val_mse: 1.1028
Epoch 2/1000
8/8 [==============================] - 0s 4ms/step - loss: 0.9595 - mse: 0.9595 - val_loss: 1.1020 - val_mse: 1.1020
Epoch 3/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.9594 - mse: 0.9594 - val_loss: 1.1008 - val_mse: 1.1008
Epoch 4/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.9584 - mse: 0.9584 - val_loss: 1.0997 - val_mse: 1.0997
Epoch 5/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.9578 - mse: 0.9578 - val_loss: 1.0979 - val_mse: 1.0979
Epoch 6/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.9566 - mse: 0.9566 - val_loss: 1.0956 - val_mse: 1.0956
Epoch 7/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.9555 - mse: 0.9555 - val_loss: 1.0927 - val_mse: 1.0927
Epoch 8/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.9521 - mse: 0.9

8/8 [==============================] - 0s 3ms/step - loss: 0.2146 - mse: 0.2146 - val_loss: 0.1707 - val_mse: 0.1707
Epoch 64/1000
8/8 [==============================] - ETA: 0s - loss: 0.0811 - mse: 0.081 - 0s 3ms/step - loss: 0.1472 - mse: 0.1472 - val_loss: 0.1666 - val_mse: 0.1666
Epoch 65/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.2227 - mse: 0.2227 - val_loss: 0.1657 - val_mse: 0.1657
Epoch 66/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.1347 - mse: 0.1347 - val_loss: 0.1657 - val_mse: 0.1657
Epoch 67/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1852 - mse: 0.1852 - val_loss: 0.1654 - val_mse: 0.1654
Epoch 68/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.1596 - mse: 0.1596 - val_loss: 0.1651 - val_mse: 0.1651
Epoch 69/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.2250 - mse: 0.2250 - val_loss: 0.1668 - val_mse: 0.1668
Epoch 70/1000
8/8 [==============================] - 0s 3ms

8/8 [==============================] - 0s 3ms/step - loss: 0.2303 - mse: 0.2303 - val_loss: 0.1525 - val_mse: 0.1525
Epoch 125/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1138 - mse: 0.1138 - val_loss: 0.1500 - val_mse: 0.1500
Epoch 126/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1167 - mse: 0.1167 - val_loss: 0.1477 - val_mse: 0.1477
Epoch 127/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1172 - mse: 0.1172 - val_loss: 0.1495 - val_mse: 0.1495
Epoch 128/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1299 - mse: 0.1299 - val_loss: 0.1489 - val_mse: 0.1489
Epoch 129/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1647 - mse: 0.1647 - val_loss: 0.1451 - val_mse: 0.1451
Epoch 130/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1428 - mse: 0.1428 - val_loss: 0.1426 - val_mse: 0.1426
Epoch 131/1000
8/8 [==============================] - 0s 4ms/step - loss: 0.1072 - mse: 0.1

8/8 [==============================] - 0s 2ms/step - loss: 0.1332 - mse: 0.1332 - val_loss: 0.1440 - val_mse: 0.1440
Epoch 187/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.1306 - mse: 0.1306 - val_loss: 0.1397 - val_mse: 0.1397
Epoch 188/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.1173 - mse: 0.1173 - val_loss: 0.1359 - val_mse: 0.1359
Epoch 189/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.2994 - mse: 0.2994 - val_loss: 0.1348 - val_mse: 0.1348
Epoch 190/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.1093 - mse: 0.1093 - val_loss: 0.1362 - val_mse: 0.1362
Epoch 191/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.0739 - mse: 0.0739 - val_loss: 0.1374 - val_mse: 0.1374
Epoch 192/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.1324 - mse: 0.1324 - val_loss: 0.1415 - val_mse: 0.1415
Epoch 193/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.1215 - mse: 0.1

8/8 [==============================] - 0s 3ms/step - loss: 0.0732 - mse: 0.0732 - val_loss: 0.1215 - val_mse: 0.1215
Epoch 248/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1638 - mse: 0.1638 - val_loss: 0.1215 - val_mse: 0.1215
Epoch 249/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.1413 - mse: 0.1413 - val_loss: 0.1203 - val_mse: 0.1203
Epoch 250/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1083 - mse: 0.1083 - val_loss: 0.1191 - val_mse: 0.1191
Epoch 251/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1237 - mse: 0.1237 - val_loss: 0.1188 - val_mse: 0.1188
Epoch 252/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1083 - mse: 0.1083 - val_loss: 0.1183 - val_mse: 0.1183
Epoch 253/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.1198 - mse: 0.1198 - val_loss: 0.1151 - val_mse: 0.1151
Epoch 254/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.1065 - mse: 0.1

8/8 [==============================] - 0s 3ms/step - loss: 0.0990 - mse: 0.0990 - val_loss: 0.1043 - val_mse: 0.1043
Epoch 309/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1856 - mse: 0.1856 - val_loss: 0.1031 - val_mse: 0.1031
Epoch 310/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1440 - mse: 0.1440 - val_loss: 0.1054 - val_mse: 0.1054
Epoch 311/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0745 - mse: 0.0745 - val_loss: 0.1053 - val_mse: 0.1053
Epoch 312/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1014 - mse: 0.1014 - val_loss: 0.1044 - val_mse: 0.1044
Epoch 313/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1553 - mse: 0.1553 - val_loss: 0.1003 - val_mse: 0.1003
Epoch 314/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.0794 - mse: 0.0794 - val_loss: 0.0989 - val_mse: 0.0989
Epoch 315/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1097 - mse: 0.1

8/8 [==============================] - 0s 2ms/step - loss: 0.1638 - mse: 0.1638 - val_loss: 0.1144 - val_mse: 0.1144
Epoch 370/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1981 - mse: 0.1981 - val_loss: 0.1170 - val_mse: 0.1170
Epoch 371/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1629 - mse: 0.1629 - val_loss: 0.1146 - val_mse: 0.1146
Epoch 372/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1576 - mse: 0.1576 - val_loss: 0.1118 - val_mse: 0.1118
Epoch 373/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.1650 - mse: 0.1650 - val_loss: 0.1093 - val_mse: 0.1093
Epoch 374/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0436 - mse: 0.0436 - val_loss: 0.1076 - val_mse: 0.1076
Epoch 375/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.2110 - mse: 0.2110 - val_loss: 0.1046 - val_mse: 0.1046
Epoch 376/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0940 - mse: 0.0

8/8 [==============================] - 0s 3ms/step - loss: 0.0940 - mse: 0.0940 - val_loss: 0.0938 - val_mse: 0.0938
Epoch 432/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.0915 - mse: 0.0915 - val_loss: 0.0946 - val_mse: 0.0946
Epoch 433/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1134 - mse: 0.1134 - val_loss: 0.0972 - val_mse: 0.0972
Epoch 434/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.1030 - mse: 0.1030 - val_loss: 0.0988 - val_mse: 0.0988
Epoch 435/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.1449 - mse: 0.1449 - val_loss: 0.0985 - val_mse: 0.0985
Epoch 436/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0663 - mse: 0.0663 - val_loss: 0.0966 - val_mse: 0.0966
Epoch 437/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0711 - mse: 0.0711 - val_loss: 0.1005 - val_mse: 0.1005
Epoch 438/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.2382 - mse: 0.2

8/8 [==============================] - 0s 2ms/step - loss: 0.0613 - mse: 0.0613 - val_loss: 0.0893 - val_mse: 0.0893
Epoch 494/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.1347 - mse: 0.1347 - val_loss: 0.0883 - val_mse: 0.0883
Epoch 495/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.0745 - mse: 0.0745 - val_loss: 0.0863 - val_mse: 0.0863
Epoch 496/1000
8/8 [==============================] - ETA: 0s - loss: 0.0473 - mse: 0.047 - 0s 2ms/step - loss: 0.1101 - mse: 0.1101 - val_loss: 0.0875 - val_mse: 0.0875
Epoch 497/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.0779 - mse: 0.0779 - val_loss: 0.0896 - val_mse: 0.0896
Epoch 498/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.1027 - mse: 0.1027 - val_loss: 0.0905 - val_mse: 0.0905
Epoch 499/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1727 - mse: 0.1727 - val_loss: 0.0892 - val_mse: 0.0892
Epoch 500/1000
8/8 [==============================] -

Epoch 555/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1368 - mse: 0.1368 - val_loss: 0.0833 - val_mse: 0.0833
Epoch 556/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1238 - mse: 0.1238 - val_loss: 0.0832 - val_mse: 0.0832
Epoch 557/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.0873 - mse: 0.0873 - val_loss: 0.0870 - val_mse: 0.0870
Epoch 558/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.0405 - mse: 0.0405 - val_loss: 0.0903 - val_mse: 0.0903
Epoch 559/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.0644 - mse: 0.0644 - val_loss: 0.0924 - val_mse: 0.0924
Epoch 560/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1014 - mse: 0.1014 - val_loss: 0.0933 - val_mse: 0.0933
Epoch 561/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1324 - mse: 0.1324 - val_loss: 0.0905 - val_mse: 0.0905
Epoch 562/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.

8/8 [==============================] - 0s 3ms/step - loss: 0.1135 - mse: 0.1135 - val_loss: 0.0816 - val_mse: 0.0816
Epoch 618/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1108 - mse: 0.1108 - val_loss: 0.0803 - val_mse: 0.0803
Epoch 619/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.0640 - mse: 0.0640 - val_loss: 0.0825 - val_mse: 0.0825
Epoch 620/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.0783 - mse: 0.0783 - val_loss: 0.0829 - val_mse: 0.0829
Epoch 621/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1361 - mse: 0.1361 - val_loss: 0.0828 - val_mse: 0.0828
Epoch 622/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1736 - mse: 0.1736 - val_loss: 0.0813 - val_mse: 0.0813
Epoch 623/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.0610 - mse: 0.0610 - val_loss: 0.0811 - val_mse: 0.0811
Epoch 624/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.0724 - mse: 0.0

8/8 [==============================] - 0s 2ms/step - loss: 0.1260 - mse: 0.1260 - val_loss: 0.0815 - val_mse: 0.0815
Epoch 679/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.0598 - mse: 0.0598 - val_loss: 0.0820 - val_mse: 0.0820
Epoch 680/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0925 - mse: 0.0925 - val_loss: 0.0838 - val_mse: 0.0838
Epoch 681/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.1184 - mse: 0.1184 - val_loss: 0.0845 - val_mse: 0.0845
Epoch 682/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.0572 - mse: 0.0572 - val_loss: 0.0855 - val_mse: 0.0855
Epoch 683/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.1003 - mse: 0.1003 - val_loss: 0.0860 - val_mse: 0.0860
Epoch 684/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.0540 - mse: 0.0540 - val_loss: 0.0851 - val_mse: 0.0851
Epoch 685/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0838 - mse: 0.0

8/8 [==============================] - 0s 2ms/step - loss: 0.1048 - mse: 0.1048 - val_loss: 0.0800 - val_mse: 0.0800
Epoch 740/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.1336 - mse: 0.1336 - val_loss: 0.0803 - val_mse: 0.0803
Epoch 741/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0848 - mse: 0.0848 - val_loss: 0.0794 - val_mse: 0.0794
Epoch 742/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0524 - mse: 0.0524 - val_loss: 0.0793 - val_mse: 0.0793
Epoch 743/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0645 - mse: 0.0645 - val_loss: 0.0794 - val_mse: 0.0794
Epoch 744/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0567 - mse: 0.0567 - val_loss: 0.0785 - val_mse: 0.0785
Epoch 745/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.1150 - mse: 0.1150 - val_loss: 0.0764 - val_mse: 0.0764
Epoch 746/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.0564 - mse: 0.0

8/8 [==============================] - 0s 3ms/step - loss: 0.0515 - mse: 0.0515 - val_loss: 0.0751 - val_mse: 0.0751
Epoch 802/1000
8/8 [==============================] - 0s 4ms/step - loss: 0.0774 - mse: 0.0774 - val_loss: 0.0756 - val_mse: 0.0756
Epoch 803/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.1568 - mse: 0.1568 - val_loss: 0.0751 - val_mse: 0.0751
Epoch 804/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0964 - mse: 0.0964 - val_loss: 0.0754 - val_mse: 0.0754
Epoch 805/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0720 - mse: 0.0720 - val_loss: 0.0765 - val_mse: 0.0765
Epoch 806/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0423 - mse: 0.0423 - val_loss: 0.0766 - val_mse: 0.0766
Epoch 807/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0715 - mse: 0.0715 - val_loss: 0.0767 - val_mse: 0.0767
Epoch 808/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.1201 - mse: 0.1

8/8 [==============================] - 0s 2ms/step - loss: 0.0415 - mse: 0.0415 - val_loss: 0.0806 - val_mse: 0.0806
Epoch 863/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0835 - mse: 0.0835 - val_loss: 0.0787 - val_mse: 0.0787
Epoch 864/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0601 - mse: 0.0601 - val_loss: 0.0781 - val_mse: 0.0781
Epoch 865/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.1158 - mse: 0.1158 - val_loss: 0.0788 - val_mse: 0.0788
Epoch 866/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.1209 - mse: 0.1209 - val_loss: 0.0802 - val_mse: 0.0802
Epoch 867/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0608 - mse: 0.0608 - val_loss: 0.0802 - val_mse: 0.0802
Epoch 868/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0484 - mse: 0.0484 - val_loss: 0.0791 - val_mse: 0.0791
Epoch 869/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0628 - mse: 0.0

8/8 [==============================] - 0s 2ms/step - loss: 0.1210 - mse: 0.1210 - val_loss: 0.0771 - val_mse: 0.0771
Epoch 924/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.0638 - mse: 0.0638 - val_loss: 0.0781 - val_mse: 0.0781
Epoch 925/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0867 - mse: 0.0867 - val_loss: 0.0799 - val_mse: 0.0799
Epoch 926/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0504 - mse: 0.0504 - val_loss: 0.0806 - val_mse: 0.0806
Epoch 927/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0569 - mse: 0.0569 - val_loss: 0.0797 - val_mse: 0.0797
Epoch 928/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.0426 - mse: 0.0426 - val_loss: 0.0802 - val_mse: 0.0802
Epoch 929/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0924 - mse: 0.0924 - val_loss: 0.0788 - val_mse: 0.0788
Epoch 930/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.0942 - mse: 0.0

8/8 [==============================] - 0s 3ms/step - loss: 0.1447 - mse: 0.1447 - val_loss: 0.0810 - val_mse: 0.0810
Epoch 986/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0472 - mse: 0.0472 - val_loss: 0.0816 - val_mse: 0.0816
Epoch 987/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.0420 - mse: 0.0420 - val_loss: 0.0831 - val_mse: 0.0831
Epoch 988/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.0848 - mse: 0.0848 - val_loss: 0.0835 - val_mse: 0.0835
Epoch 989/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.0767 - mse: 0.0767 - val_loss: 0.0802 - val_mse: 0.0802
Epoch 990/1000
8/8 [==============================] - ETA: 0s - loss: 0.3430 - mse: 0.343 - 0s 3ms/step - loss: 0.0829 - mse: 0.0829 - val_loss: 0.0762 - val_mse: 0.0762
Epoch 991/1000
8/8 [==============================] - 0s 3ms/step - loss: 0.0260 - mse: 0.0260 - val_loss: 0.0739 - val_mse: 0.0739
Epoch 992/1000
8/8 [==============================] -

### 12. Model Prediction on Individual Observation

[Back to Top](#Table-of-Contents)

In [101]:
model.predict(X[[0]]),model.predict(X[[1]])

(array([[1.7110282]], dtype=float32), array([[1.6637356]], dtype=float32))

In [102]:
sc.inverse_transform(model.predict(X[[0]]))

array([[180284.52]], dtype=float32)

In [103]:
y[[0]]

array([[2.01120333]])

In [104]:
X[0]

array([-0.71774056, -0.68599434,  1.39326109,  2.01641149,  0.55299984,
        2.15371621])

In [105]:
sc.inverse_transform(y[0])

array([192261.83])

### 13. Testing Model

[Back to Top](#Table-of-Contents)

In [106]:
model.predict(sc.inverse_transform(X_test))

array([[ 73391.664],
       [ 62318.695],
       [113067.08 ],
       [ 58832.008],
       [ 99049.27 ],
       [124724.03 ],
       [ 47660.227],
       [102452.734],
       [ 87329.164],
       [119600.81 ],
       [ 76001.37 ],
       [ 48203.68 ],
       [ 62621.227],
       [ 31481.99 ]], dtype=float32)

In [107]:
sc.inverse_transform(y_test)

array([[108733.99],
       [ 97483.56],
       [156991.12],
       [ 96712.8 ],
       [129917.04],
       [191050.39],
       [ 71498.49],
       [152211.77],
       [125370.37],
       [182901.99],
       [110352.25],
       [ 77798.83],
       [103282.38],
       [ 35673.41]])

### 14. RMSE Score

[Back to Top](#Table-of-Contents)

In [100]:
math.sqrt(pow(abs(model.predict(sc.inverse_transform(X_test))-sc.inverse_transform(y_test)),2).mean())

40906.757023740945